# LIQUIBASE
outputChangeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml

# MYSQL
url=jdbc:mysql://127.0.0.1:3306/ApIsEcUrEdB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
username=ToUpDaTeUsErR
password=3JiaU9k3LGza4676b3eNPTWSZkZ4Y8vdw46p23iN
driver=com.mysql.cj.jdbc.Driver