-- Utilisateur avec droits SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX
CREATE USER IF NOT EXISTS 'ToUpDaTeUsErR'@'%' IDENTIFIED BY '3JiaU9k3LGza4676b3eNPTWSZkZ4Y8vdw46p23iN';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'ToUpDaTeUsErR'@'%';
REVOKE SHOW DATABASES ON *.* FROM 'ToUpDaTeUsErR'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES ON ApIsEcUrEdB.* TO 'ToUpDaTeUsErR'@'%';

FLUSH PRIVILEGES;